site_name: hoom

theme:
  name: material
  logo: docs/logo.png
  palette:
    # scheme: slate # (darkmode)
    primary: black
    accent: amber
  highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
            
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.details
  - pymdownx.superfences