# Site info
site_name: hoom
site_url: https://berrysauce.me/hoom
site_author: Paul Haedrich
site_description: >-
  Build your own HomeKit Bridge & Accessories with Hoom. This is 
  the documentation for the Hoom Python package.

# Repository info
repo_name: berrysauce/hoom
repo_url: https://github.com/berrysauce/hoom
edit_uri: /blob/main/docs/{path}

# Copyright
copyright: Copyright &copy; 2023 Paul Haedrich

# Theme configuration
theme:
  name: material
  logo: https://raw.githubusercontent.com/berrysauce/hoom/main/docs/logo.png
  palette:
    # scheme: slate # (darkmode)
    primary: black
    accent: amber
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
  highlightjs: true

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx

# Markdown extensions
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Navigation
nav:
  - Home: 
    - index.md
    - Getting Started:
      - Installing & Updating: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
      - Examples: getting-started/examples.md
    - Basics:
      - Bridge: basics/bridge.md
      - Accessories:
        - basics/accessories.md
        - Lamp: basics/accessories/lamp.md
        - Switch: basics/accessories/switch.md
        - Temperature Sensor: basics/accessories/temperature-sensor.md
      - Responses: basics/responses.md
    - Web UI:
      - How to use the Web UI: web/guide.md
      - Hoom API: web/api.md
    - Advanced:
      - Custom Accessories: advanced/custom-accessories.md
    - Security:
      - How to keep your Bridge secure: security/guide.md
  - Changelog: https://github.com/berrysauce/hoom/releases
  - Donate: https://github.com/sponsors/berrysauce
  - Code of Conduct: https://github.com/berrysauce/hoom/blob/main/CODE_OF_CONDUCT.md
  - Security Policy: https://github.com/berrysauce/hoom/blob/main/SECURITY.md
  - Legal Disclaimer: https://github.com/berrysauce/hoom/blob/main/DISCLAIMER.md
