version: 2.1

orbs:
  python: circleci/python@1.5.0  # Replace x.y.z with the latest stable version of the Python orb.

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Replace with the Python version you want to use (e.g., 3.6, 3.7, 3.8, 3.9).
    steps:
      - checkout

      # Set up Python environment
      - python/set-up-python

      # Restore Poetry cache (if any)
      - restore_cache:
          keys:
            - v1-poetry-{{ checksum "pyproject.toml" }}

      # Install project dependencies
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python -
            export PATH=$HOME/.local/bin:$PATH
      - run:
          name: Install dependencies
          command: poetry install

      # Save Poetry cache
      - save_cache:
          key: v1-poetry-{{ checksum "pyproject.toml" }}
          paths:
            - ~/.cache/pypoetry
            - ~/.local/share/virtualenvs

      # Run tests
      # - run:
      #    name: Run tests
      #    command: poetry run pytest

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main  # Adjust this branch filter as needed.
