version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout

      # Install project dependencies
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://install.python-poetry.org | python -
            export PATH=$HOME/.local/bin:$PATH
      - run:
          name: Install dependencies
          command: poetry install

      # Run tests
      # - run:
      #    name: Run tests
      #    command: poetry run pytest

workflows:
  build:
    jobs:
      - build
